---
- name: Deploy Food Application (web app)
  hosts: n2
  become: yes

  tasks:
  - name: Install Git
    yum:
      name: git
      state: present

  - name: Host code repo
    git:
      repo: https://github.com/CeeyIT-Solutions/food3.git
      dest: /var/www/html
...
