---
- name: Variable Testing for Username
  hosts: g1
  become: yes
  vars:
    myusername: Toyosi D

  tasks:
   - name: Update Dynamic Page
     template:
       src: dynamic.j2
       dest: /var/www/html/dynamic.html
...